export const oracleAbi = [
  {
    inputs: [],
    name: 'getRate',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getSupplyRate',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getSpread',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getVolatility',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getTermRate',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getFullBenchmark',
    outputs: [
      { name: 'rate', type: 'uint256' },
      { name: 'supply', type: 'uint256' },
      { name: 'spread', type: 'uint256' },
      { name: 'vol', type: 'uint256' },
      { name: 'term7d', type: 'uint256' },
      { name: 'updated', type: 'uint256' },
      { name: 'sources', type: 'uint256' },
      { name: 'configured', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'periodsBack', type: 'uint256' }],
    name: 'getHistoricalRate',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'numSources',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'sourcesConfigured',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'historyIndex',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'circuitBreakerActive',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'lastCircuitBreakerTrip',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'riskLevel',
    outputs: [{ name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const

export const swapAbi = [
  {
    inputs: [
      { name: 'fixedRateBps', type: 'uint256' },
      { name: 'duration', type: 'uint256' },
    ],
    name: 'createSwap',
    outputs: [{ name: 'swapId', type: 'uint256' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ name: 'swapId', type: 'uint256' }],
    name: 'joinSwap',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ name: 'swapId', type: 'uint256' }],
    name: 'settle',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'swapId', type: 'uint256' }],
    name: 'closeSwap',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'swapId', type: 'uint256' }],
    name: 'cancelSwap',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getSwapCount',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'swapId', type: 'uint256' }],
    name: 'getSwap',
    outputs: [
      { name: 'fixedPayer', type: 'address' },
      { name: 'floatingPayer', type: 'address' },
      { name: 'notional', type: 'uint256' },
      { name: 'fixedRateBps', type: 'uint256' },
      { name: 'duration', type: 'uint256' },
      { name: 'startedAt', type: 'uint256' },
      { name: 'fixedPayerMargin', type: 'uint256' },
      { name: 'floatingPayerMargin', type: 'uint256' },
      { name: 'status', type: 'uint8' },
      { name: 'totalSettlements', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'swapId', type: 'uint256' }],
    name: 'getUnrealizedPnL',
    outputs: [
      { name: 'fixedPayerPnL', type: 'int256' },
      { name: 'floatingPayerPnL', type: 'int256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getCurrentRate',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'maxResults', type: 'uint256' }],
    name: 'getSettleableSwaps',
    outputs: [{ name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'maxResults', type: 'uint256' }],
    name: 'getExpiredSwaps',
    outputs: [{ name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'maxResults', type: 'uint256' }],
    name: 'getAtRiskSwaps',
    outputs: [{ name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    name: 'ownerOf',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    name: 'tokenURI',
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MARGIN_BPS',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'SETTLEMENT_INTERVAL',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const

export const consumerAbi = [
  {
    inputs: [],
    name: 'getRiskScore',
    outputs: [{ name: 'score', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getCurrentBorrowRate',
    outputs: [
      { name: 'rateBps', type: 'uint256' },
      { name: 'regime', type: 'string' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getAdaptiveCollateralRatio',
    outputs: [{ name: 'ratioBps', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getSourceDiversityScore',
    outputs: [{ name: 'diversityBps', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'currentFixedRate', type: 'uint256' },
      { name: 'notional', type: 'uint256' },
      { name: 'rateShockBps', type: 'int256' },
    ],
    name: 'getStressTestPnL',
    outputs: [{ name: 'pnlImpact', type: 'int256' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const

export const ccipReceiverAbi = [
  {
    inputs: [],
    name: 'getRate',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getFullBenchmark',
    outputs: [
      { name: 'rate', type: 'uint256' },
      { name: 'supply', type: 'uint256' },
      { name: 'spread', type: 'uint256' },
      { name: 'vol', type: 'uint256' },
      { name: 'term7d', type: 'uint256' },
      { name: 'updated', type: 'uint256' },
      { name: 'sources', type: 'uint256' },
      { name: 'configured', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'periodsBack', type: 'uint256' }],
    name: 'getHistoricalRate',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getRiskMetadata',
    outputs: [
      { name: '_riskLevel', type: 'uint8' },
      { name: '_circuitBreakerActive', type: 'bool' },
      { name: '_riskScore', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const

export const paymentGateAbi = [
  {
    inputs: [{ name: 'consumer', type: 'address' }],
    name: 'getCredits',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pricePerCredit',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'paymentToken',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'treasury',
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalCreditsIssued',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalCreditsConsumed',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalRevenue',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: '', type: 'address' }],
    name: 'totalSpent',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'consumer', type: 'address' },
      { name: 'minCredits', type: 'uint256' },
    ],
    name: 'hasCredits',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'amount', type: 'uint256' }],
    name: 'purchaseCredits',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const

export const erc20Abi = [
  {
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const

export const aiInsightAbi = [
  {
    inputs: [],
    name: 'getInsight',
    outputs: [
      { name: '_riskLevel', type: 'uint8' },
      { name: '_rateDirection', type: 'uint8' },
      { name: '_spreadHealth', type: 'uint8' },
      { name: '_marketRegime', type: 'uint8' },
      { name: '_riskScore', type: 'uint256' },
      { name: '_anomalyDetected', type: 'bool' },
      { name: '_lastAnalyzedAt', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'isHighRisk',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'insightIndex',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'periodsBack', type: 'uint256' }],
    name: 'getHistoricalRiskScore',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const
