[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts@5.0.2/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/contracts-ccip/=lib/chainlink-ccip/chains/evm/",
]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/b6652bb1dac64d0a96a7a01043b44ee4"
base_sepolia = "https://base-sepolia.infura.io/v3/b6652bb1dac64d0a96a7a01043b44ee4"
arb_sepolia = "https://arbitrum-sepolia.infura.io/v3/b6652bb1dac64d0a96a7a01043b44ee4"
op_sepolia = "https://optimism-sepolia.infura.io/v3/b6652bb1dac64d0a96a7a01043b44ee4"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
arb_sepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
op_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia-optimistic.etherscan.io/api" }