/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as CrossChainRouteImport } from './routes/cross-chain'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetSymbolRouteImport } from './routes/asset/$symbol'

const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const CrossChainRoute = CrossChainRouteImport.update({
  id: '/cross-chain',
  path: '/cross-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetSymbolRoute = AssetSymbolRouteImport.update({
  id: '/asset/$symbol',
  path: '/asset/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/compare': typeof CompareRoute
  '/cross-chain': typeof CrossChainRoute
  '/methodology': typeof MethodologyRoute
  '/payment': typeof PaymentRoute
  '/pipeline': typeof PipelineRoute
  '/risk': typeof RiskRoute
  '/swap': typeof SwapRoute
  '/asset/$symbol': typeof AssetSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/compare': typeof CompareRoute
  '/cross-chain': typeof CrossChainRoute
  '/methodology': typeof MethodologyRoute
  '/payment': typeof PaymentRoute
  '/pipeline': typeof PipelineRoute
  '/risk': typeof RiskRoute
  '/swap': typeof SwapRoute
  '/asset/$symbol': typeof AssetSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/compare': typeof CompareRoute
  '/cross-chain': typeof CrossChainRoute
  '/methodology': typeof MethodologyRoute
  '/payment': typeof PaymentRoute
  '/pipeline': typeof PipelineRoute
  '/risk': typeof RiskRoute
  '/swap': typeof SwapRoute
  '/asset/$symbol': typeof AssetSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/compare'
    | '/cross-chain'
    | '/methodology'
    | '/payment'
    | '/pipeline'
    | '/risk'
    | '/swap'
    | '/asset/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/compare'
    | '/cross-chain'
    | '/methodology'
    | '/payment'
    | '/pipeline'
    | '/risk'
    | '/swap'
    | '/asset/$symbol'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/compare'
    | '/cross-chain'
    | '/methodology'
    | '/payment'
    | '/pipeline'
    | '/risk'
    | '/swap'
    | '/asset/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  CompareRoute: typeof CompareRoute
  CrossChainRoute: typeof CrossChainRoute
  MethodologyRoute: typeof MethodologyRoute
  PaymentRoute: typeof PaymentRoute
  PipelineRoute: typeof PipelineRoute
  RiskRoute: typeof RiskRoute
  SwapRoute: typeof SwapRoute
  AssetSymbolRoute: typeof AssetSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-chain': {
      id: '/cross-chain'
      path: '/cross-chain'
      fullPath: '/cross-chain'
      preLoaderRoute: typeof CrossChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$symbol': {
      id: '/asset/$symbol'
      path: '/asset/$symbol'
      fullPath: '/asset/$symbol'
      preLoaderRoute: typeof AssetSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  CompareRoute: CompareRoute,
  CrossChainRoute: CrossChainRoute,
  MethodologyRoute: MethodologyRoute,
  PaymentRoute: PaymentRoute,
  PipelineRoute: PipelineRoute,
  RiskRoute: RiskRoute,
  SwapRoute: SwapRoute,
  AssetSymbolRoute: AssetSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
